### ISSUE TITLE
Bug in versions after 6.2.0, if the string starts with double ل

### ISSUE THREAD

**Issue by muhannad17** [khaled-alshamaa/ar-php#64]
Assalam Alaikum, 

First, thank you for your amazing work on this package. I have been using it for a while now and it has been very helpful.

I am writing to report a bug while using utf8Glyphs function. The bug occurs when the function is passed a string that starts with two consecutive ل characters (for example, للاستخدام). In this case, the function will throw an undefined offset: -1 error on Arabic.php at line 2400.

The error occurs because the function is looking for the previous character at index -2. However, since the string starts with two consecutive ل characters, there is no previous character at index -2.

I am not familiar enough with the code to submit a pull request to fix this bug. However, I would be happy to provide more information or help in any way that I can.

![image](https://github.com/khaled-alshamaa/ar-php/assets/8653369/413cae68-7d12-45f3-a34e-da8c40cd4245)

Thank you,

**Comment by khaled-alshamaa** [comment]
Wa Alaykum Assalam my friend Muhannad,

Thank you for reporting this bug. It is well-known and has been reported before ([issue #60](https://github.com/khaled-alshamaa/ar-php/issues/60)) and resolved in the latest version 6.3.4 (check related [changelog announcement](https://github.com/khaled-alshamaa/ar-php/blob/master/CHANGELOG.md#whats-new-in-arphp-634-release-date-apr-5-2023)). Please do upgrade to fix it ;-)

By the way, there is no v6.3.6 yet! As far as I know ;-P

**Comment by muhannad17** [comment]
Thank you for your response. and I'm sorry about the incorrect version number. 

I tried 6.3.4 again and it's still have the same problem.

ErrorException
Undefined offset: -1 
![image](https://github.com/khaled-alshamaa/ar-php/assets/8653369/a67fd2cf-1c74-4c58-b0bc-37c65ffde586)

**Comment by khaled-alshamaa** [comment]
Ah, I am sorry that I close this issue before get your confirmation! Also, I hate to say that it is working on my machine, because that means the problem might occur with other users without my notice and simply pass the testing phase successfully, which is the worst scenario.

Therefore, let me start by thanking you for insisting on reporting this issue. Then main source of miss catching this issue is that I still using the [deprecated](https://wiki.php.net/rfc/reclassify_e_strict) `E_STRICT` error reporting level :-(

You may use the following command ahead of your script to overcome this warning message for now, output will be generated perfectly fine, and I will work on fixing the source of the error message in the next patch/version of the library :-)

```php
error_reporting(E_ALL & ~E_WARNING);
```

**Comment by khaled-alshamaa** [comment]
Please let me know if that resolved your issue for now. 
You can get rid of that error reporting setting once you upgrade to the next batch/version of the library, as I already fixed it in the backend source code.

**Comment by muhannad17** [comment]
Thank you for the fix. I'm already back using version 6.2 for now until the next release. 

I will try to test the latest source code (master branch).

**Comment by khaled-alshamaa** [comment]
Please close this issue once you confirm that the latest source code (master branch) has fixed it, and wait for the new release very soon.
